---

#
# Copyright (c) 2014 Davide Guerri <davide.guerri@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Configure Nova API
  ini_file: dest=/etc/nova/nova.conf
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    # Common settings
    - section:  DEFAULT
      option:   my_ip
      value:    "{{ my_ip }}"
    - section:  DEFAULT
      option:   enabled_apis
      value:    "{{ nova_enabled_apis }}"
    - section:  DEFAULT
      option:   osapi_compute_listen
      value:    "{{ nova_api_bind_host }}"
    - section:  DEFAULT
      option:   osapi_compute_listen_port
      value:    "{{ nova_port }}"
    - section:  DEFAULT
      option:   ec2_listen
      value:    "{{ nova_ec2_bind_host }}"
    - section:  DEFAULT
      option:   ec2_listen_port
      value:    "{{ nova_ec2_port }}"
    - section:  DEFAULT
      option:   metadata_listen
      value:    "{{ nova_metadata_bind_host }}"
    - section:  DEFAULT
      option:   metadata_listen_port
      value:    "{{ nova_metadata_port }}"
    - section:  DEFAULT
      option:   logdir
      value:    "{{ nova_log_dir }}"
    # Message Queue
    - section:  DEFAULT
      option:   rpc_backend
      value:    rabbit
    - section:  DEFAULT
      option:   rabbit_host
      value:    "{{ rabbit_hostname }}"
    - section:  DEFAULT
      option:   rabbit_userid
      value:    "{{ rabbit_username }}"
    - section:  DEFAULT
      option:   rabbit_password
      value:    "{{ rabbit_pass }}"
    # Neutron
    - section:  DEFAULT
      option:   network_api_class
      value:    nova.network.neutronv2.api.API
    - section:  DEFAULT
      option:   neutron_url
      value:    "{{ neutron_protocol }}://{{ neutron_hostname }}:{{ neutron_port }}"
    - section:  DEFAULT
      option:   neutron_auth_strategy
      value:    keystone
    - section:  DEFAULT
      option:   neutron_admin_tenant_name
      value:    service
    - section:  DEFAULT
      option:   neutron_admin_username
      value:    "{{ neutron_admin_username }}"
    - section:  DEFAULT
      option:   neutron_admin_password
      value:    "{{ neutron_pass }}"
    - section:  DEFAULT
      option:   neutron_admin_auth_url
      value:    "{{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_admin_port }}/v2.0"
    - section:  DEFAULT
      option:   linuxnet_interface_driver
      value:    nova.network.linux_net.LinuxOVSInterfaceDriver
    - section:  DEFAULT
      option:   firewall_driver
      value:    nova.virt.firewall.NoopFirewallDriver
    - section:  DEFAULT
      option:   security_group_api
      value:    neutron
    - section:  DEFAULT
      option:   service_neutron_metadata_proxy
      value:    true
    - section:  DEFAULT
      option:   neutron_metadata_proxy_shared_secret
      value:    "{{ metadata_secret }}"
    # Keystone
    - section:  DEFAULT
      option:   auth_strategy
      value:    keystone
    - section:  keystone_authtoken
      option:   auth_uri
      value:    "{{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_port }}/v2.0"
    - section:  keystone_authtoken
      option:   auth_host
      value:    "{{ keystone_hostname }}"
    - section:  keystone_authtoken
      option:   auth_port
      value:    "{{ keystone_admin_port }}"
    - section:  keystone_authtoken
      option:   auth_protocol
      value:    "{{ keystone_protocol }}"
    - section:  keystone_authtoken
      option:   admin_tenant_name
      value:    service
    - section:  keystone_authtoken
      option:   admin_user
      value:    "{{ nova_user }}"
    - section:  keystone_authtoken
      option:   admin_password
      value:    "{{ nova_pass }}"
    - section:  glance
      option:   host
      value:    "{{ glance_hostname }}"
    - section:  glance
      option:   port
      value:    "{{ glance_port }}"
    - section:  glance
      option:   protocol
      value:    "{{ glance_protocol }}"
  notify:
    - Restart Nova API
